### ISSUE TITLE
Error detected while processing command line: E492: Not an editor command: FzfRg

### ISSUE THREAD

**Issue by jrekier** [naps62/zk#1]
Hey @naps62, 

Been looking for a minimal portable implementation of zettelkasten for a while. And I really like what I'm seeing here. 

I have a problem with the `search` command, though. When I try to use it with `zk search`, this shows up:

![image](https://user-images.githubusercontent.com/9407736/109223091-74ac3f80-77ba-11eb-9095-d80532cf81a8.png)

Thanks for your help!

**Comment by naps62** [comment]
Hi @jrekier 
I think this is because you might be missing the [fzf[vim](https://github.com/junegunn/fzf.vim) plugin. It wasn't referenced in the readme. I just pushed an update to fix that

Could you let me know if installing the plugin (along with both fzf and ripgrep) fixes it?

**Comment by jrekier** [comment]
Hi @naps62 thanks for your reply. 
The strange thing is I already have that plugin installed. I purged my plugins and reinstalled them but that did not help ... The error is still there.

**Comment by jrekier** [comment]
fyi, here is a list of the relevant plugins I use

```
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'yuki-yano/fzf-preview.vim'
Plug 'BurntSushi/ripgrep'
```

**Comment by naps62** [comment]
@jrekier I tried reproducing your issue (I replaced my plugins to use yours instead), but I couldn't :confused: everything worked for me

What is your output for `:verbose command FzfRg`?

For reference, this is what I get:

```
:verbose command FzfRg
    Name              Args Address Complete    Definition
!   FzfRg             *                        call fzf#vim#grep("rg --column --line-number --no-heading --color=always --smart-case -- ".shellescape(<q-args>), 1, fzf#vim#with_preview(), <bang>0)
        Last set from ~/projects/dotfiles/config/nvim/plugged/fzf.vim/plugin/fzf.vim line 42
```

**Comment by francklays** [comment]
Hi @jrekier, I get the same error as you, did you find what was causing it ? Thx

My output for `:verbose command FzfRg` is `No user defined command found` (translated from French)

**Comment by sekel** [comment]
You either need to set `let g:fzf_vim.command_prefix = 'Fzf'` in `.vimrc` or you need to change the the command on line 7 in `$HOME/.zk/libexec/zk-search` to be `$EDITOR -c ":set autochdir | :Rg"`. 

For reference https://github.com/junegunn/fzf.vim/tree/master?tab=readme-ov-file#commands
